
import { PhotoQuote } from './types';

export const PHOTO_QUOTES: PhotoQuote[] = [
  { text: "You don’t take a photograph, you make it.", author: "Ansel Adams" },
  { text: "Your first 10,000 photographs are your worst.", author: "Henri Cartier-Bresson" },
  { text: "If your pictures aren’t good enough, you aren’t close enough.", author: "Robert Capa" },
  { text: "Photography is the story I fail to put into words.", author: "Destin Sparks" },
  { text: "When words become unclear, I shall focus with photographs.", author: "Ansel Adams" },
  { text: "In photography there is a reality so subtle that it becomes more real than reality.", author: "Alfred Stieglitz" },
  { text: "The camera is an instrument that teaches people how to see without a camera.", author: "Dorothea Lange" },
  { text: "I don’t trust words. I trust pictures.", author: "Gilles Peress" },
  { text: "Taking pictures is savoring life intensely, every hundredth of a second.", author: "Ruth Bernhard" },
  { text: "To me, photography is an art of observation. It’s about finding something interesting in an ordinary place.", author: "Elliott Erwitt" },
  { text: "A good photograph is one that communicates a fact, touches the heart and leaves the viewer a changed person for having seen it.", author: "Irving Penn" },
  { text: "The eye should learn to listen before it looks.", author: "Robert Frank" },
  { text: "A photograph is a secret about a secret. The more it tells you the less you know.", author: "Diane Arbus" },
  { text: "Photography is a way of feeling, of touching, of loving.", author: "Aaron Siskind" },
  { text: "Which of my photographs is my favorite? The one I’m going to take tomorrow.", author: "Imogen Cunningham" },
  { text: "The camera makes you forget you're there. It’s not like you are hiding but you are forgetting, you are actually looking.", author: "Annie Leibovitz" },
  { text: "If I could tell the story in words, I wouldn't need to lug around a camera.", author: "Lewis Hine" },
  { text: "Don’t pack your camera until you’ve left the location.", author: "Joe McNally" },
  { text: "Light makes photography. Embrace light. Admire it. Love it. But above all, know light.", author: "George Eastman" },
  { text: "It is more important to click with people than to click the shutter.", author: "Alfred Eisenstaedt" },
  { text: "Skill in photography is acquired by practice and not by purchase.", author: "Percy W. Harris" },
  { text: "A portrait is not made in the camera but on either side of it.", author: "Edward Steichen" },
  { text: "Great photography is about depth of feeling, not depth of field.", author: "Peter Adams" },
  { text: "My life is shaped by the urgent need to wander and observe, and my camera is my passport.", author: "Steve McCurry" },
  { text: "Photography is the only language that can be understood anywhere in the world.", author: "Bruno Barbey" },
  { text: "A camera is a tool for learning how to see without a camera.", author: "Dorothea Lange" },
  { text: "Essentially what photography is is life lit up.", author: "Sam Abell" },
  { text: "Look and think before opening the shutter. The heart and mind are the true lens of the camera.", author: "Yousuf Karsh" },
  { text: "I suspect it is for one's self that one takes photographs.", author: "Ruth Bernhard" },
  { text: "Photography for me is not looking, it’s feeling.", author: "Don McCullin" },
  { text: "Every viewer is going to get a different thing. That’s the thing about painting, photography, cinema.", author: "David Lynch" },
  { text: "Landscape photography is the supreme test of the photographer - and often the supreme disappointment.", author: "Ansel Adams" },
  { text: "I am a tourist in my own life.", author: "Garry Winogrand" },
  { text: "The camera is an excuse to be somewhere you otherwise don’t belong.", author: "Susan Meiselas" },
  { text: "The best thing about a picture is that it never changes, even when the people in it do.", author: "Andy Warhol" },
  { text: "You fill up the frame with feelings, energy, discovery, and risk, and leave room enough for someone else to get in.", author: "Joel Meyerowitz" },
  { text: "Photography takes an instant out of time, altering life by holding it still.", author: "Dorothea Lange" },
  { text: "The picture is the result of the creative moment.", author: "Sebastião Salgado" },
  { text: "Beauty can be seen in all things, seeing and composing the beauty is what separates the snapshot from the photograph.", author: "Matt Hardy" },
  { text: "I love the people I photograph. I mean, they're my friends. I've never met most of them or I don't know them at all, yet through my images I live with them.", author: "Bruce Gilden" },
  { text: "To photograph is to hold one's breath, when all faculties converge to capture fleeting reality.", author: "Henri Cartier-Bresson" },
  { text: "A photograph is a document that keeps the memory from fading.", author: "Mary Ellen Mark" },
  { text: "A photograph is like a recipe - a memory of a meal.", author: "Carrie Mae Weems" },
  { text: "Your photography is a record of your living, for anyone who really sees.", author: "Paul Strand" },
  { text: "Photography deals with the ephemeral. It is the art of the half-second.", author: "Berenice Abbott" },
  { text: "I never questioned what to do. I just went on with it.", author: "Saul Leiter" },
  { text: "Photography is a small voice, at best, but sometimes one photograph, or a group of them, can lure our sense of awareness.", author: "W. Eugene Smith" },
  { text: "Subjectivity is the most important thing for me.", author: "Nan Goldin" },
  { text: "It's one thing to make a picture of what a person looks like, it's another thing to make a portrait of who they are.", author: "Paul Caponigro" },
  { text: "Always shoot for the print.", author: "Gordon Parks" },
  { text: "I really believe there are things nobody would see if I didn’t photograph them.", author: "Diane Arbus" },
  { text: "There are no rules for good photographs, there are only good photographs.", author: "Ansel Adams" },
  { text: "The camera is an instrument that teaches people how to see without a camera.", author: "Dorothea Lange" },
  { text: "To photograph is to put on the same line of sight the head, the eye and the heart.", author: "Henri Cartier-Bresson" },
  { text: "Everything is a subject. Every subject has a rhythm. To feel it is to be the artist.", author: "Edward Weston" },
  { text: "The camera can be a shield, but it can also be a weapon.", author: "Giles Peress" },
  { text: "Be who you are and say what you feel.", author: "Bill Cunningham" },
  { text: "Photography is about capturing what is in front of you.", author: "Mary Ellen Mark" },
  { text: "The more I see, the less I know for sure.", author: "John Lennon" },
  { text: "Black and white are the colors of photography. To me they symbolize the alternatives of hope and despair.", author: "Robert Frank" },
  { text: "What you see is what you get.", author: "Lee Friedlander" },
  { text: "There are only two colors in the world, black and white.", author: "Robert Frank" },
  { text: "I've always been more interested in what I can't see than what I can.", author: "Man Ray" },
  { text: "I don't think you can ever be finished with photography.", author: "Graciela Iturbide" },
  { text: "A photograph is a memory in the making.", author: "Steve McCurry" },
  { text: "Photography is an act of love.", author: "Nan Goldin" },
  { text: "I just like to look.", author: "Stephen Shore" },
  { text: "The miracle of photography is that it allows you to capture a moment that will never happen again.", author: "Rene Burri" },
  { text: "The more you look, the more you see.", author: "Joel Meyerowitz" },
  { text: "Photography is a way of saying, 'This is what I saw.'", author: "Walker Evans" },
  { text: "I don't photograph things, I photograph the way they make me feel.", author: "Eve Arnold" },
  { text: "The camera is a simple machine.", author: "Garry Winogrand" },
  { text: "I shoot for myself.", author: "Daido Moriyama" },
  { text: "Photography is a lonely craft.", author: "Don McCullin" },
  { text: "I want to see what things look like photographed.", author: "Garry Winogrand" },
  { text: "Photography is the recording of light.", author: "Laszlo Moholy-Nagy" },
  { text: "I am always looking for the light.", author: "Annie Leibovitz" },
  { text: "Photography is a journey of discovery.", author: "Minor White" },
  { text: "I see things through the camera.", author: "Margaret Bourke-White" },
  { text: "Photography is a mirror of life.", author: "Tina Modotti" },
  { text: "I don't plan anything.", author: "Nobuyoshi Araki" },
  { text: "Photography is a dialogue.", author: "Paolo Pellegrin" },
  { text: "The camera is a physical thing.", author: "William Klein" },
  { text: "I am interested in the world as it is.", author: "William Eggleston" },
  { text: "Photography is a tool for social change.", author: "Gordon Parks" },
  { text: "I am a visual person.", author: "David Bailey" },
  { text: "Photography is a form of poetry.", author: "Mario Giacomelli" },
  { text: "The camera is a window.", author: "Josef Koudelka" },
  { text: "I am a collector of moments.", author: "Raghubir Singh" },
  { text: "Photography is a dance.", author: "Alex Webb" },
  { text: "I am inspired by the street.", author: "Fan Ho" },
  { text: "Photography is a performance.", author: "Cindy Sherman" },
  { text: "I am a witness.", author: "James Nachtwey" },
  { text: "Photography is a conversation.", author: "Danny Lyon" },
  { text: "I am looking for the truth.", author: "Richard Avedon" },
  { text: "Photography is a mystery.", author: "Gregory Crewdson" },
  { text: "I am exploring the unknown.", author: "Hiroshi Sugimoto" },
  { text: "Photography is a meditation.", author: "Michael Kenna" },
  { text: "I am chasing the shadow.", author: "Trent Parke" },
  { text: "Photography is a weapon against forgetting.", author: "Zanele Muholi" },
  { text: "I am painting with light.", author: "Man Ray" },
  { text: "Photography is an investigation.", author: "Taryn Simon" },
  { text: "I am seeking the essence.", author: "Edward Weston" },
  { text: "Photography is a symphony of tones.", author: "Ansel Adams" },
  { text: "I am documenting the human condition.", author: "Mary Ellen Mark" },
  { text: "Photography is an encounter.", author: "Graciela Iturbide" },
  { text: "I am listening to the landscape.", author: "Fay Godwin" },
  { text: "Photography is a silent language.", author: "Fan Ho" },
  { text: "I am tracing the history.", author: "Joel Sternfeld" },
  { text: "Photography is a way to survive.", author: "Robert Capa" },
  { text: "I am capturing the soul.", author: "Yousuf Karsh" },
  { text: "Photography is an act of defiance.", author: "Ai Weiwei" },
  { text: "I am chasing the dream.", author: "Sarah Moon" },
  { text: "Photography is a window into the soul.", author: "Julia Margaret Cameron" },
  { text: "I am building a world.", author: "Jeff Wall" },
  { text: "Photography is a question.", author: "Alec Soth" },
  { text: "I am seeking the beauty in the mundane.", author: "Stephen Shore" },
  { text: "Photography is a time machine.", author: "Shomei Tomatsu" },
  { text: "I am exploring the silence.", author: "Harry Callahan" },
  { text: "Photography is a bridge.", author: "Rene Burri" },
  { text: "I am seeking the extraordinary.", author: "Steve McCurry" },
  { text: "Photography is a heartbeat.", author: "Daido Moriyama" },
  { text: "I am observing the light.", author: "Saul Leiter" },
  { text: "Photography is a witness to history.", author: "Robert Capa" },
  { text: "I am discovering the rhythm.", author: "Alex Webb" },
  { text: "Photography is a song.", author: "Bruce Davidson" },
  { text: "I am searching for the connection.", author: "Platon" },
  { text: "Photography is an expression of the spirit.", author: "Minor White" },
  { text: "I am chasing the vanishing world.", author: "Edward Curtis" },
  { text: "Photography is a tool for memory.", author: "Sally Mann" },
  { text: "I am documenting the transition.", author: "Mitch Epstein" },
  { text: "Photography is a way of seeing.", author: "John Berger" },
  { text: "I am looking for the story.", author: "Philip-Lorca diCorcia" },
  { text: "Photography is a light in the dark.", author: "Gordon Parks" },
  { text: "I am seeking the symmetry.", author: "Andreas Gursky" },
  { text: "Photography is an intervention.", author: "Martin Parr" },
  { text: "I am questioning the reality.", author: "Thomas Demand" },
  { text: "Photography is a fragment of time.", author: "Garry Winogrand" },
  { text: "I am exploring the identity.", author: "Catherine Opie" },
  { text: "Photography is a visual diary.", author: "Nan Goldin" },
  { text: "I am chasing the light of the city.", author: "Ray K. Metzker" },
  { text: "Photography is a journey through space.", author: "Luigi Ghirri" },
  { text: "I am seeking the silence of the forest.", author: "Shinzo Maeda" },
  { text: "Photography is a whisper.", author: "Masahisa Fukase" },
  { text: "I am tracing the light on the wall.", author: "Uta Barth" },
  { text: "Photography is an open door.", author: "William Klein" },
  { text: "I am looking for the geometry.", author: "Henri Cartier-Bresson" },
  { text: "Photography is a way to belong.", author: "Mary Ellen Mark" },
  { text: "I am exploring the intimacy.", author: "Sally Mann" },
  { text: "Photography is a reflection.", author: "Lee Friedlander" },
  { text: "I am seeking the balance.", author: "Robert Mapplethorpe" },
  { text: "Photography is a record of the heart.", author: "W. Eugene Smith" },
  { text: "I am chasing the motion.", author: "Ernst Haas" },
  { text: "Photography is a discovery of self.", author: "Diane Arbus" },
  { text: "I am looking for the hidden.", author: "Brassai" },
  { text: "Photography is a tool for liberation.", author: "Ernest Cole" },
  { text: "I am seeking the light of the morning.", author: "Eliot Porter" },
  { text: "Photography is a visual adventure.", author: "Burk Uzzle" },
  { text: "I am exploring the textures.", author: "Edward Weston" },
  { text: "Photography is a gift of sight.", author: "Paul Strand" },
  { text: "I am chasing the echo.", author: "Naoya Hatakeyama" },
  { text: "Photography is a bridge between worlds.", author: "Sebastião Salgado" },
  { text: "I am looking for the truth in the face.", author: "August Sander" },
  { text: "Photography is a silent witness.", author: "Don McCullin" },
  { text: "I am exploring the suburbs.", author: "Bill Owens" },
  { text: "Photography is a way to remember.", author: "Nobuyoshi Araki" },
  { text: "I am seeking the color of life.", author: "Joel Meyerowitz" },
  { text: "Photography is a fragment of the world.", author: "Stephen Shore" },
  { text: "I am chasing the light of the sea.", author: "Hiroshi Sugimoto" },
  { text: "Photography is a tool for understanding.", author: "Lewis Hine" },
  { text: "I am looking for the magic in the street.", author: "Vivian Maier" },
  { text: "Photography is an act of discovery.", author: "Todd Hido" },
  { text: "I am seeking the architecture of light.", author: "Julius Shulman" },
  { text: "Photography is a silent poem.", author: "Fan Ho" },
  { text: "I am exploring the edge.", author: "Mark Cohen" },
  { text: "Photography is a way to look at the world.", author: "William Eggleston" },
  { text: "I am chasing the light of the desert.", author: "Richard Misrach" },
  { text: "Photography is a record of existence.", author: "Nadar" },
  { text: "I am seeking the essence of the moment.", author: "Bill Brandt" },
  { text: "Photography is a visual symphony.", author: "Ansel Adams" },
  { text: "I am looking for the soul of the city.", author: "Berenice Abbott" },
  { text: "Photography is a tool for reflection.", author: "Minor White" },
  { text: "I am exploring the body.", author: "John Coplans" },
  { text: "Photography is a way to connect.", author: "Danny Lyon" },
  { text: "I am chasing the light of the forest.", author: "Shinzo Maeda" },
  { text: "Photography is a record of the journey.", author: "Robert Frank" },
  { text: "I am seeking the truth in the land.", author: "Timothy O'Sullivan" },
  { text: "Photography is a visual dialogue.", author: "Paolo Pellegrin" },
  { text: "I am looking for the story in the eyes.", author: "Dorothea Lange" },
  { text: "Photography is an act of presence.", author: "Rinko Kawauchi" },
  { text: "I am exploring the space between.", author: "Hiroshi Sugimoto" },
  { text: "Photography is a silent conversation.", author: "Saul Leiter" },
  { text: "I am seeking the light of the mountains.", author: "Ansel Adams" },
  { text: "Photography is a visual memory.", author: "Mary Ellen Mark" },
  { text: "I am chasing the light of the sky.", author: "Alfred Stieglitz" },
  { text: "Photography is a tool for discovery.", author: "Karl Blossfeldt" },
  { text: "I am looking for the pattern.", author: "Andreas Gursky" },
  { text: "Photography is a visual poem.", author: "Mario Giacomelli" },
  { text: "I am exploring the landscape of the mind.", author: "Minor White" },
  { text: "Photography is a way to find beauty.", author: "Imogen Cunningham" },
  { text: "I am seeking the light in the eyes.", author: "Yousuf Karsh" },
  { text: "Photography is a record of human spirit.", author: "Dorothea Lange" },
  { text: "I am chasing the light of the soul.", author: "Edward Steichen" },
  { text: "Photography is a visual truth.", author: "Paul Strand" },
  { text: "I am looking for the beauty in the ordinary.", author: "Walker Evans" },
  { text: "Photography is a silent song.", author: "Bruce Davidson" },
  { text: "I am exploring the texture of the world.", author: "Edward Weston" },
  { text: "Photography is a way to see the unseen.", author: "Man Ray" },
  { text: "I am seeking the light of the truth.", author: "W. Eugene Smith" },
  { text: "Photography is a visual record of life.", author: "Tina Modotti" },
  { text: "I am chasing the light of the street.", author: "Helen Levitt" },
  { text: "Photography is a tool for social justice.", author: "Gordon Parks" },
  { text: "I am looking for the story in the light.", author: "Annie Leibovitz" },
  { text: "Photography is an act of seeing.", author: "John Berger" },
  { text: "I am exploring the world through the lens.", author: "Margaret Bourke-White" },
  { text: "Photography is a visual journey.", author: "Steve McCurry" },
  { text: "I am seeking the light of the heart.", author: "Aaron Siskind" },
  { text: "Photography is a record of our time.", author: "Robert Capa" },
  { text: "I am chasing the light of the future.", author: "Laszlo Moholy-Nagy" },
  { text: "Photography is a visual language.", author: "Bruno Barbey" },
  { text: "I am looking for the rhythm of life.", author: "Henri Cartier-Bresson" },
  { text: "Photography is a silent witness to history.", author: "Robert Capa" },
  { text: "I am exploring the human condition.", author: "Sebastião Salgado" },
  { text: "Photography is a way to hold onto the past.", author: "Sally Mann" },
  { text: "I am seeking the light of the land.", author: "Ansel Adams" },
  { text: "Photography is a visual expression of self.", author: "Diane Arbus" },
  { text: "I am looking for the beauty in the struggle.", author: "Dorothea Lange" },
  { text: "Photography is an act of love for the world.", author: "Nan Goldin" },
  { text: "I am chasing the light of the shadows.", author: "Ray K. Metzker" },
  { text: "Photography is a visual document of the journey.", author: "Robert Frank" },
  { text: "I am seeking the light of the city night.", author: "Brassai" },
  { text: "Photography is a way to find one's place.", author: "Mary Ellen Mark" },
  { text: "I am exploring the architecture of the mind.", author: "Thomas Demand" },
  { text: "Photography is a silent poem of the world.", author: "Fan Ho" },
  { text: "I am looking for the light in the dark places.", author: "Gordon Parks" },
  { text: "Photography is an act of discovery of the soul.", author: "Minor White" },
  { text: "I am chasing the light of the fleeting moment.", author: "Henri Cartier-Bresson" },
  { text: "Photography is a visual record of our presence.", author: "Walker Evans" },
  { text: "I am seeking the light of the natural world.", author: "Eliot Porter" },
  { text: "Photography is a tool for memory and emotion.", author: "Sally Mann" },
  { text: "I am exploring the identity of the land.", author: "Robert Adams" },
  { text: "Photography is a silent song of the spirit.", author: "Mario Giacomelli" },
  { text: "I am looking for the geometry of life.", author: "Henri Cartier-Bresson" },
  { text: "Photography is an act of witnessing.", author: "James Nachtwey" },
  { text: "I am seeking the light of the human heart.", author: "W. Eugene Smith" },
  { text: "Photography is a visual bridge between people.", author: "Rene Burri" },
  { text: "I am chasing the light of the unknown path.", author: "Todd Hido" },
  { text: "Photography is a tool for understanding the world.", author: "Lewis Hine" },
  { text: "I am exploring the beauty of the structure.", author: "Bernd and Hilla Becher" },
  { text: "Photography is a silent whisper of time.", author: "Masahisa Fukase" },
  { text: "I am looking for the truth in the silence.", author: "Hiroshi Sugimoto" },
  { text: "Photography is an act of creative will.", author: "Edward Weston" },
  { text: "I am seeking the light of the everyday.", author: "Stephen Shore" },
  { text: "Photography is a visual record of our humanity.", author: "Dorothea Lange" },
  { text: "I am chasing the light of the wide world.", author: "Steve McCurry" },
  { text: "Photography is a tool for connecting with others.", author: "Danny Lyon" },
  { text: "I am exploring the textures of existence.", author: "Aaron Siskind" },
  { text: "Photography is a silent symphony of light.", author: "Ansel Adams" },
  { text: "I am looking for the soul of the image.", author: "Minor White" },
  { text: "Photography is an act of presence in the world.", author: "Rinko Kawauchi" },
  { text: "I am seeking the light of the historical moment.", author: "Robert Capa" },
  { text: "Photography is a visual diary of our lives.", author: "Nan Goldin" },
  { text: "I am chasing the light of the urban landscape.", author: "Lee Friedlander" },
  { text: "Photography is a tool for reflecting on life.", author: "John Berger" },
  { text: "I am exploring the mystery of the portrait.", author: "Richard Avedon" },
  { text: "Photography is a silent witness to our journey.", author: "Josef Koudelka" },
  { text: "I am looking for the light of the morning sun.", author: "Sam Abell" },
  { text: "Photography is an act of sharing our vision.", author: "William Klein" },
  { text: "I am seeking the light of the internal world.", author: "Francesca Woodman" },
  { text: "Photography is a visual record of our environment.", author: "Robert Adams" },
  { text: "I am chasing the light of the open road.", author: "Stephen Shore" },
  { text: "Photography is a tool for revealing the world.", author: "Karl Blossfeldt" },
  { text: "I am exploring the silence of the soul.", author: "Michael Kenna" },
  { text: "Photography is a silent poem of light and shadow.", author: "Fan Ho" },
  { text: "I am looking for the beauty in the shadows.", author: "Saul Leiter" },
  { text: "Photography is an act of exploring reality.", author: "Garry Winogrand" },
  { text: "I am seeking the light of the true self.", author: "Diane Arbus" },
  { text: "Photography is a visual record of our connection.", author: "Platon" },
  { text: "I am chasing the light of the changing tides.", author: "Hiroshi Sugimoto" },
  { text: "Photography is a tool for documenting our history.", author: "Margaret Bourke-White" },
  { text: "I am exploring the beauty of the mundane world.", author: "William Eggleston" },
  { text: "Photography is a silent witness to the truth.", author: "Don McCullin" },
  { text: "I am looking for the light of the human spirit.", author: "Yousuf Karsh" },
  { text: "Photography is an act of capturing the soul.", author: "Julia Margaret Cameron" },
  { text: "I am seeking the light of the natural spirit.", author: "Paul Strand" },
  { text: "Photography is a visual bridge between the past and future.", author: "Sally Mann" },
  { text: "I am chasing the light of the modern world.", author: "Laszlo Moholy-Nagy" },
  { text: "Photography is a tool for creating our own reality.", author: "Jeff Wall" },
  { text: "I am exploring the space within the image.", author: "Uta Barth" },
  { text: "Photography is a silent conversation with the world.", author: "Elliott Erwitt" },
  { text: "I am looking for the light of the decisive moment.", author: "Henri Cartier-Bresson" },
  { text: "Photography is an act of falling in love with what you see.", author: "Joel Meyerowitz" },
  { text: "I am seeking the light of the universal language.", author: "Bruno Barbey" },
  { text: "Photography is a visual record of our collective memory.", author: "Mary Ellen Mark" },
  { text: "I am chasing the light of the eternal truth.", author: "W. Eugene Smith" },
  { text: "Photography is a tool for finding the extraordinary in the ordinary.", author: "Ruth Bernhard" },
  { text: "I am exploring the landscape of the human heart.", author: "Aaron Siskind" },
  { text: "Photography is a silent song of the world's beauty.", author: "Ansel Adams" },
  { text: "I am looking for the light in every single frame.", author: "Joe McNally" },
  { text: "Photography is an act of making the invisible visible.", author: "Berenice Abbott" },
  { text: "I am seeking the light of the true vision.", author: "Edward Weston" },
  { text: "Photography is a visual journey through the soul.", author: "Minor White" },
  { text: "I am chasing the light of the world as it is.", author: "Robert Frank" },
  { text: "Photography is a tool for exploring our existence.", author: "Garry Winogrand" },
  { text: "I am exploring the geometry of the soul.", author: "Henri Cartier-Bresson" },
  { text: "Photography is a silent witness to our time on earth.", author: "Robert Capa" },
  { text: "I am looking for the light in the eyes of humanity.", author: "Dorothea Lange" },
  { text: "Photography is an act of celebrating life.", author: "Andy Warhol" },
  { text: "I am seeking the light of the inner truth.", author: "Minor White" },
  { text: "Photography is a visual record of our wonder.", author: "National Geographic" },
  { text: "I am chasing the light until the very end.", author: "Bill Cunningham" },
  { text: "Photography is a tool for memory and love.", author: "Nan Goldin" },
  { text: "I am exploring the world one frame at a time.", author: "Steve McCurry" },
  { text: "Photography is a silent poem written in light.", author: "Ansel Adams" }
];
